import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kuriocity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = (
    <header>
      <div className="text-center p-8 my-6">
        <h1 className="text-3xl text-black-500 font-bold"><Link href="/">Kuriocity</Link></h1>
      </div>
    </header>
  );
  const footer = (
    <footer className="text-center border-t mt-6 py-4">
      <p>Obsessive consumption of the right information &gt;&gt;&gt;</p>
    </footer>
  );
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-4xl px-4">
        {header}
        {children}
        {footer}
        </div>
      </body>
    </html>
  );
}
